export const authConstants = {
  LOGIN_REQUEST : 'LOGIN_REQUEST',
  LOGIN_FAILURE : 'LOGIN_FAILURE',
  LOGIN_SUCCESS : 'LOGIN_SUCCESS',
  LOGOUT_REQUEST : 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE : 'LOGOUT_FAILURE',

}

export const userConstants = {
  USER_REGISTER_REQUEST : 'USER_REGISTER_REQUEST',
  USER_REGISTER_FAILURE : 'USER_REGISTER_FAILURE',
  USER_REGISTER_SUCCESS : 'USER_REGISTER_SUCCESS'
}

export const categoryConstants = {
  GET_ALL_CATEGORIES_REQUEST : 'GET_ALL_CATEGORIES_REQUEST',
  GET_ALL_CATEGORIES_FAILURE : 'GET_ALL_CATEGORIES_FAILURE',
  GET_ALL_CATEGORIES_SUCCESS : 'GET_ALL_CATEGORIES_SUCCESS',
  ADD_NEW_CATEGORY_REQUEST : 'ADD_NEW_CATEGORY_REQUEST',
  ADD_NEW_CATEGORY_FAILURE : 'ADD_NEW_CATEGORY_FAILURE',
  ADD_NEW_CATEGORY_SUCCESS : 'ADD_NEW_CATEGORY_SUCCESS'
}

export const eventConstants = {
  EVENT_REGISTER_REQUEST : 'EVENT_REGISTER_REQUEST',
  EVENT_REGISTER_FAILURE : 'EVENT_REGISTER_FAILURE',
  EVENT_REGISTER_SUCCESS : 'EVENT_REGISTER_SUCCESS',
  GET_EVENT_REQUEST : 'GET_EVENT_REQUEST',
  GET_EVENT_FAILURE : 'GET_EVENT_FAILURE',
  GET_EVENT_SUCCESS : 'GET_EVENT_SUCCESS'
}